### ISSUE TITLE
Bad test result using pretrained model

### ISSUE THREAD

**Issue by zeng32** [zhechen/PLARD#3]
Hi,

After running the test with the pre-trained model, the output results are stored in /output/results.
By using the evaluation code from devkit_road download from KITTI website, the following is the result:
Starting evaluation ...
Available categories are: ['um_lane', 'um_road', 'umm_road', 'uu_road']
Execute evaluation for category um_lane ...
Searching for submitted files with prefix: um_lane_
Computing evaluation scores...
MaxF: 86.93 
AvgPrec: 90.74 
PRE_wp: 86.91 
REC_wp: 86.95 
FPR_wp: 1.17 
FNR_wp: 13.05 
Finished evaluating category: um_lane 
Execute evaluation for category um_road ...
Searching for submitted files with prefix: um_road_
Computing evaluation scores...
MaxF: 89.62 
AvgPrec: 93.21 
PRE_wp: 89.32 
REC_wp: 89.93 
FPR_wp: 2.12 
FNR_wp: 10.07 
Finished evaluating category: um_road 
Execute evaluation for category umm_road ...
Searching for submitted files with prefix: umm_road_
Computing evaluation scores...
MaxF: 83.00 
AvgPrec: 89.42 
PRE_wp: 77.65 
REC_wp: 89.14 
FPR_wp: 8.03 
FNR_wp: 10.86 
Finished evaluating category: umm_road 
Execute evaluation for category uu_road ...
Searching for submitted files with prefix: uu_road_
Computing evaluation scores...
MaxF: 81.50 
AvgPrec: 87.35 
PRE_wp: 79.03 
REC_wp: 84.13 
FPR_wp: 3.52 
FNR_wp: 15.87 
Finished evaluating category: uu_road 
Successfully finished evaluation for 4 categories: ['um_lane', 'um_road', 'umm_road', 'uu_road']

Apparently, the result is far from what you posted in your paper.
Would you please help me figure out why?
Btw, a lot of bugs are found in the evaluation code, and I have to correct them in order to run.

**Comment by zhechen** [comment]
Thanks for helping me evaluate my model. I have checked my model by my side, and the obtained results are 96.32/97.47/96.13/96.79 for UM/UMM/UU/URBAN, respectively. 

I am sorry that I am not sure why you are getting these erroneous results. Some potential problems may include: not fixing normalization parameters; not transforming perspective results into bev results; not reading images appropriately... BTW, this project basically does not produce lane detection results.

If you found clear bugs or errors in this project, please commit pull request and I can merge them in this project.

Please refer to my updated explanation for other information.

**Comment by zeng32** [comment]
Thanks for the reply!
Would you please share the result evaluation code with us?
Just make sure that we are using the same code to evaluate the results which are generated by the same pre-train code.
Thank you!

**Comment by zhechen** [comment]
I am basically using the sample code from KITTI's devkit, "simpleExample_generateBEVResults.py", to help transform the output perspective results into bev view and submit the results on KITTI's evaluation server.

**Comment by zeng32** [comment]
Alright then, thanks a lot for the info.

**Comment by zeng32** [comment]
Hi,

Thanks a lot for the reply!
My BEV results look exactly the same as yours(you shared in dropbox) except in file size.
What weird about is when I submit them in zip file to the server, I got following error:

Starting evaluation...
Available categories are: ['um_road', 'umm_road', 'uu_road', 'um_lane']
Execute pixel-based evaluation for category um_road ...
Searching for submitted files with prefix: um_road_
Encountered three channels in file um_road_000055. Will try to fix this...
Checking first file to identify file format...
The result file format: probability map
Encountered three channels in file um_road_000046. Will try to fix this...
Encountered three channels in file um_road_000011. Will try to fix this...
Encountered three channels in file um_road_000028. Will try to fix this...
Encountered three channels in file um_road_000060. Will try to fix this...
Encountered three channels in file um_road_000081. Will try to fix this...
Encountered three channels in file um_road_000033. Will try to fix this...
Encountered three channels in file um_road_000091. Will try to fix this...
Encountered three channels in file um_road_000017. Will try to fix this...
Encountered three channels in file um_road_000004. Will try to fix this...
Encountered three channels in file um_road_000026. Will try to fix this...
Encountered three channels in file um_road_000044. Will try to fix this...
Encountered three channels in file um_road_000039. Will try to fix this...
Encountered three channels in file um_road_000008. Will try to fix this...
Encountered three channels in file um_road_000087. Will try to fix this...
Encountered three channels in file um_road_000034. Will try to fix this...
Encountered three channels in file um_road_000073. Will try to fix this...
Encountered three channels in file um_road_000047. Will try to fix this...
Encountered three channels in file um_road_000003. Will try to fix this...
Encountered three channels in file um_road_000058. Will try to fix this...
Encountered three channels in file um_road_000002. Will try to fix this...
Encountered three channels in file um_road_000094. Will try to fix this...
Encountered three channels in file um_road_000012. Will try to fix this...
Encountered three channels in file um_road_000029. Will try to fix this...
Encountered three channels in file um_road_000010. Will try to fix this...
Encountered three channels in file um_road_000083. Will try to fix this...
Computing evaluation scores...
AssertionError: Encountered shape mismatch!
Critical Error! Will now abort evaluation...
An error occured while processing your results.
Please make sure that the data in your zip archive has the right format!

I have double-checked that the shape of my BEV results is identical to yours.
Now I'm stuck at the evaluation, would you please be so kind to share your testing results and the evaluation code in the dropbox?

Thanks again!

**Comment by zhechen** [comment]
It says that "Encountered three channels". Probably, you should use grayscale images which have only 1 channel.

**Comment by zeng32** [comment]
After writing the png file with only one channel, we got the right result.
Thanks very much for the info!
